// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQdOjloqsVOVbCCcBGtS_bJh54To-4kw',
    appId: '1:217467965491:web:303230b012947132819346',
    messagingSenderId: '217467965491',
    projectId: 'alpha-flutter-health',
    authDomain: 'alpha-flutter-health.firebaseapp.com',
    storageBucket: 'alpha-flutter-health.firebasestorage.app',
    measurementId: 'G-Z2PPMNB6RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtRIH0foAtqwZ7W2y00nwVcI51yz10ig',
    appId: '1:217467965491:android:7218df22114b46b6819346',
    messagingSenderId: '217467965491',
    projectId: 'alpha-flutter-health',
    storageBucket: 'alpha-flutter-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmjHXfM_FwdtP-x9QnBAEdqaz4Bv4NkY',
    appId: '1:217467965491:ios:b6045dab369f2d6d819346',
    messagingSenderId: '217467965491',
    projectId: 'alpha-flutter-health',
    storageBucket: 'alpha-flutter-health.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmjHXfM_FwdtP-x9QnBAEdqaz4Bv4NkY',
    appId: '1:217467965491:ios:b6045dab369f2d6d819346',
    messagingSenderId: '217467965491',
    projectId: 'alpha-flutter-health',
    storageBucket: 'alpha-flutter-health.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQdOjloqsVOVbCCcBGtS_bJh54To-4kw',
    appId: '1:217467965491:web:2ec384d1c4fe5a5e819346',
    messagingSenderId: '217467965491',
    projectId: 'alpha-flutter-health',
    authDomain: 'alpha-flutter-health.firebaseapp.com',
    storageBucket: 'alpha-flutter-health.firebasestorage.app',
    measurementId: 'G-J5PW9BRM53',
  );
}
